[package]
name = "bibfetch"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
lexopt = "0.3.1"
mlua = { version = "0.10.3", features = ["anyhow", "luajit", "serialize", "send"] }
parking_lot = "0.12.3"
rayon = "1.10.0"
serde_json = "1.0.140"
ureq = "3.0.11"
wasmtime = "31.0.0"
